version: "2"

services:
  bitcoind:
    container_name: bitcoind
    hostname: bitcoind
    image: legacycode/bitcoind:latest
    restart: unless-stopped
    volumes:
      - bitcoind-data:/home/bitcoin/.bitcoin
    ports:
      - 8333:8333
    command: [
      "-server",
      "-txindex",
    ]

volumes:
  bitcoind-data:
