version: 2

jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: echo 'export DOCKER_TAG=${DOCKER_USERNAME}/bitcoind:${CIRCLE_BRANCH}' >> $BASH_ENV
      - run: docker info
      - run: docker build --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` --build-arg VCS_REF=$CIRCLE_SHA1 . -t ${DOCKER_TAG}
      - run: docker run --rm ${DOCKER_TAG} -version
      - run: docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
      - run: docker push ${DOCKER_TAG}

workflows:
  version: 2
  commit:
    jobs:
      - build
  nightly:
    jobs:
      - build
    triggers:
      - schedule:
          cron: "0 2 * * *"
          filters:
            branches:
              only:
                - nightly
