version: 2

jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: echo 'export DOCKER_TAG=${DOCKER_USERNAME}/bitcoind:${CIRCLE_BRANCH}' >> $BASH_ENV
      - run: docker info
      - run: docker build --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` --build-arg VCS_REF=$CIRCLE_SHA1 . -t ${DOCKER_TAG}
      - run: docker run --rm ${DOCKER_TAG} -version
  nightly:
    docker:
      - image: circleci/node:10.0-browsers
    steps:
      - checkout
      - run:
          name: Trigger docker nightly remotely
          command: |
            curl -H 'Content-Type: application/json' \
            --data '{"source_type": "Branch", "source_name": "nightly"}' \
            -X POST ${DOCKERHUB_TRIGGER}

workflows:
  version: 2
  commit:
    jobs:
      - build
  nightly:
    jobs:
      - nightly
    triggers:
      - schedule:
          cron: "0 2 * * *"
          filters:
            branches:
              only:
                - nightly
