version: 2

jobs: 

  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      # install actual docker version
      - run: sudo apt-get remove docker docker-engine docker.io containerd runc
      - run: sudo apt-get update
      - run: sudo apt-get install apt-transport-https ca-certificates curl gnupg-agent software-properties-common
      - run: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
      - run: sudo apt-key fingerprint 0EBFCD88
      - run: sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
      - run: sudo apt-get update
      - run: sudo apt-get install docker-ce docker-ce-cli containerd.io

      # enable experimental docker features for buildx
      - run: echo 'export DOCKER_CLI_EXPERIMENTAL=enabled' >> $BASH_ENV
      - run: docker info

      # register qemu and create multi-architecture build instance
      - run: docker run --rm --privileged docker/binfmt:a7996909642ee92942dcd6cff44b9b95f08dad64
      - run: docker buildx create --name mybuilder
      - run: docker buildx use mybuilder
      - run: docker buildx inspect --bootstrap
      
      # build and push bintcoind
      - checkout
      - run: echo 'export DOCKER_TAG=${DOCKER_USERNAME}/bitcoind:${CIRCLE_BRANCH}${CIRCLE_TAG}' >> $BASH_ENV
      - run: docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
      - run: |
          docker buildx build \
          --platform linux/amd64,linux/arm64,linux/386,linux/arm/v7 \
          --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
          --build-arg VCS_REF=$CIRCLE_SHA1 . -t ${DOCKER_TAG} --push

workflows: 
  version: 2
  tagged: 
    jobs: 
      - build: 
          filters: 
            branches: 
              ignore: /.*/
            tags: 
              only: /^v.*/
  untagged: 
    jobs: 
      - build
